### ISSUE TITLE
15 билет

### ISSUE THREAD

**Issue by wiserax2037** [vegtamr-ab/computational-maths#11]
![image](https://user-images.githubusercontent.com/55760917/71981288-242ef700-3233-11ea-958d-2a6f01379d3f.png)

Следует подкорректировать выделенное на 

![image](https://user-images.githubusercontent.com/55760917/71981390-5dfffd80-3233-11ea-9091-35994f806920.png)

Иначе реально перепутать 
`nLn-1(x)` с 
`nLn - 1(x)` (что  бы 1(х) не значило хD)

**Comment by Yang-Pi** [comment]
да, разумно
