### ISSUE TITLE
17 билет - опечатки

### ISSUE THREAD

**Issue by wiserax2037** [vegtamr-ab/computational-maths#12]
![image](https://user-images.githubusercontent.com/55760917/72071880-d6cb8c00-32fd-11ea-92ce-d5d62fbabb58.png)

Вместо равно в выделенном, наверное, имелся в виду знак минуса.

**Comment by wiserax2037** [comment]
![image](https://user-images.githubusercontent.com/55760917/72072547-45f5b000-32ff-11ea-9375-1069878aa489.png)


Пропущена степень -1. 


UPD:  чуть дальше
 ![image](https://user-images.githubusercontent.com/55760917/72072662-81907a00-32ff-11ea-932e-fc71d7354324.png)

**Comment by wiserax2037** [comment]
Что ?
![image](https://user-images.githubusercontent.com/55760917/72080295-983dcd80-330d-11ea-9b73-e7ab3ade8e74.png)

**Comment by Yang-Pi** [comment]
> ![image](https://user-images.githubusercontent.com/55760917/72072547-45f5b000-32ff-11ea-9375-1069878aa489.png)
> 
> Пропущена степень -1.
> 
> UPD: чуть дальше
> ![image](https://user-images.githubusercontent.com/55760917/72072662-81907a00-32ff-11ea-932e-fc71d7354324.png)

да, ништяк, спасибо, в этой формуле вообще спутались \lambda и \alpha
