### ISSUE TITLE
19. Доделать оформление обозначения предела

### ISSUE THREAD

**Issue by wiserax2037** [vegtamr-ab/computational-maths#15]
![image](https://user-images.githubusercontent.com/55760917/72158961-748d8c80-33cc-11ea-92f8-6455cdb83f2d.png)

Есть основания предполагать что здесь операнды надо поменять местами. Ссылаюсь на другие конспекты. (у меня тоже y(t) - x(t) )
![image](https://user-images.githubusercontent.com/55760917/72159048-9f77e080-33cc-11ea-843a-db293fe60bab.png)

**Comment by vegtamr-ab** [comment]
У меня в конспекте `x(t)-y(t)`.

Но насколько я знаю высшую математику (а знаю я её плохо), если при таком стремлении предел от `a-b` равен `0`, то и предел от `b-a` будет равен `0`. Если моя догадка ошибочна, я переверну. Если нет, сноску сделаю. И да, в любом случае там надо будет под пределом написать `t -> infty`

**Comment by Yang-Pi** [comment]
Ошибки никакой нет.
Можно убедиться, открыв 285 стр. учебника "Вычислительная математика" С.М. Устинова
![image](https://user-images.githubusercontent.com/55200686/72161149-a0127600-33d0-11ea-8e73-26242d2c2a98.png)
