### ISSUE TITLE
19. Добавить описание слова "language" в контексте формулы

### ISSUE THREAD

**Issue by wiserax2037** [vegtamr-ab/computational-maths#16]
![image](https://user-images.githubusercontent.com/55760917/72159870-558ffa00-33ce-11ea-8bf7-be6b093af4a0.png)

???

**Comment by wiserax2037** [comment]
Кстати, насколько я понял, мы нигде не используем норму, которую берём в этой строке

**Comment by vegtamr-ab** [comment]
Язык эпсилон-дельта же, ну. Сноска будет, получается.
