### ISSUE TITLE
Билет 25

### ISSUE THREAD

**Issue by wiserax2037** [vegtamr-ab/computational-maths#22]
![image](https://user-images.githubusercontent.com/55760917/72289791-e4b24180-365c-11ea-8d3a-9663e25c722a.png)
наверное пропущено троеточие(возможно это предполагалось как очевидное, но всё же)

**Comment by Yang-Pi** [comment]
Спокойно, Леха, я сейчас как раз этот билет читаю, сейчас все будет в порядке!

**Comment by wiserax2037** [comment]
![image](https://user-images.githubusercontent.com/55760917/72290564-8d14d580-365e-11ea-88c9-15633088b2a0.png)
Грубая ошибка - неявный метод трапеций имеет 2 стпень точности.

**Comment by wiserax2037** [comment]
@Yang-Pi )))
