### ISSUE TITLE
17.Ошибка в Теореме 2 из "7 теорем о матричных ф-иях"

### ISSUE THREAD

**Issue by BurnBirdX7** [vegtamr-ab/computational-maths#23]
Последнее равенство `S*Σ(a_k*A^k)*S^-1 = Σ(a_k*A^k)` некорректно.
Вместо этого должно быть `S*Σ(a_k*A^k)*S^-1 = S*f(A)*S^-1`.
В итоге получается `f(B) = ... = S*f(A)*S^-1, ЧТД`

(Чек пособие Устинова раздел П3.5)

**Comment by Yang-Pi** [comment]
конечно! спасибо
