### ISSUE TITLE
[Выч. мат.] RKF45 - вопрос

### ISSUE THREAD

**Issue by wiserax2037** [vegtamr-ab/computational-maths#24]
![image](https://user-images.githubusercontent.com/55760917/72334116-e10ad300-36cd-11ea-9761-940db82b7b75.png)
Не ошибка/опечатка, просто интересно почему сумма до 6-ти.

**Comment by vegtamr-ab** [comment]
Для метода 5 степени точности надо 6 раз вычислить функцию. Для метода 4 - 4 раза, но это, можно сказать, для однообразия - в методе 4 степени точности `P5` и `P6` будут равны 0.
