### ISSUE TITLE
Поправка

### ISSUE THREAD

**Issue by wiserax2037** [vegtamr-ab/computational-maths#6]
файл - https://github.com/vegtamr-ab/computational-maths/blob/master/pdf/1-finite-differences.pdf

Насколько понимаю выделенное - лишнее.
![image](https://user-images.githubusercontent.com/55760917/71696559-5f11d480-2dc6-11ea-98fe-07d5af5732f1.png)

Основываюсь на 214 стр. пособия Устинова
 https://vk.com/doc12303364_515198572?hash=0897b82d1feeb326e7&dl=86aa27091c02786f43
Скриншот оригинала:
![image](https://user-images.githubusercontent.com/55760917/71696705-b7e16d00-2dc6-11ea-8589-32cf65113d0b.png)

**Comment by wiserax2037** [comment]
Ниже, в формуле (4) возможно имеет смысл заменить первую часть 
![image](https://user-images.githubusercontent.com/55760917/71697002-a6e52b80-2dc7-11ea-92d8-6e35df8fc675.png)

на 
![image](https://user-images.githubusercontent.com/55760917/71696951-85843f80-2dc7-11ea-80d5-a2f9408e84a8.png)

с адаптацией.
Источник тот же

**Comment by Yang-Pi** [comment]
> файл - https://github.com/vegtamr-ab/computational-maths/blob/master/pdf/1-finite-differences.pdf
> 
> Насколько понимаю выделенное - лишнее.
> ![image](https://user-images.githubusercontent.com/55760917/71696559-5f11d480-2dc6-11ea-98fe-07d5af5732f1.png)
> 
> Основываюсь на 214 стр. пособия Устинова
> https://vk.com/doc12303364_515198572?hash=0897b82d1feeb326e7&dl=86aa27091c02786f43
> Скриншот оригинала:
> ![image](https://user-images.githubusercontent.com/55760917/71696705-b7e16d00-2dc6-11ea-8589-32cf65113d0b.png)

Не лишнее, потому что черта и определенный интеграл слева от нее являются частью комментария "Перегруппируем члены равенства и _проинтегрируем от a до b_"; все таки пишем конспект, поэтому предпочтительнее сокращенный вид

**Comment by Yang-Pi** [comment]
> Ниже, в формуле (4) возможно имеет смысл заменить первую часть
> ![image](https://user-images.githubusercontent.com/55760917/71697002-a6e52b80-2dc7-11ea-92d8-6e35df8fc675.png)
> 
> на
> ![image](https://user-images.githubusercontent.com/55760917/71696951-85843f80-2dc7-11ea-80d5-a2f9408e84a8.png)
> 
> с адаптацией.
> Источник тот же

Если речь идет о замене нижнего индекса на индекс в скобках, то согласен

**Comment by Yang-Pi** [comment]
![image](https://user-images.githubusercontent.com/55200686/71710396-23e6c400-2e0d-11ea-8499-21283f15b22d.png)
А стоит ли игра свечей? По-моему выглядит менее аккуратно..
