### ISSUE TITLE
Имена файлов

### ISSUE THREAD

**Issue by wiserax2037** [vegtamr-ab/computational-maths#7]
Будет корректно заменить название файла 
1-finite-differences.pdf 
на
1-2-4-finite-differences.pdf
Или по-другому, так как там рассмотрены ещё 2 и 4 билет.
И кст, Ярик, когда будет 3 билет про линейные разностные?))

**Comment by vegtamr-ab** [comment]
pdf еще не обновлён, исходники уже исправлены в соттветствии с билетами
